name: Deploy DirectiveIQ to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: rg-compute-japan
  AZURE_APP_NAME: directiveiq
  AZURE_REGION: japanwest

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az version

      - name: Deploy infrastructure with Bicep
        run: |
          az deployment group create \
            --resource-group $AZURE_RESOURCE_GROUP \
            --template-file deploy/main.bicep \
            --parameters @deploy/parameters.prod.json

      - name: Zip FastAPI app
        run: |
          cd app
          zip -r ../directiveiq-app.zip .
          cd ..

      - name: Deploy app code to Azure Web App
        run: |
          az webapp deployment source config-zip \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_APP_NAME \
            --src directiveiq-app.zip
